### ISSUE TITLE
Test enmerkar-underscore on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/enmerkar-underscore#149]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [x] Requirements are compiled with Python 3.8
- [x] Tests are run on Python 3.8 and 3.11
- [x] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [x] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [x] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by feanil** [comment]
Looks like this one is a bit complicated, it depends on an old version of `markey` which has a regex that isn't valid in Python 3.11/3.12 so we'll probably need to fork that and update this library to use a corrected version.

**Comment by mariajgrimaldi** [comment]
[Here's](https://github.com/openedx/edx-platform/commit/4e84d435c1043d79270f29c001ebc763d48628fa) is the latest commit made to [conf/locale/babel_underscore.cfg](https://github.com/openedx/edx-platform/blob/master/conf/locale/babel_underscore.cfg#L1-L6), where this library is used. The commit was made by @awais786 in . Do you know if this library is still in the translation process?

**Comment by mariajgrimaldi** [comment]
I unassigned myself since @feanil is already working on fixing the issue with the unmaintained requirement. Thank you!

**Comment by feanil** [comment]
I took a quick look and it looks like we do still need this extractor because of all the underscore templates that still exist in edx-platform.
